apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: controller-manager
spec:
  ipFamily: IPv4
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ include "kube-controller-manager.port" . }}
      protocol: TCP
  selector:
    app: kubernetes
    role: controller-manager