---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: vpn-shoot
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    garden.sapcloud.io/role: system-component
    app: vpn-shoot
    origin: gardener
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: vpn-shoot
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/secret-vpn-shoot-dh: {{ include (print $.Template.BasePath "/secret-dh.yaml") . | sha256sum }}
        checksum/secret-vpn-shoot-tlsauth: {{ include (print $.Template.BasePath "/secret-tlsauth.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        origin: gardener
        gardener.cloud/role: system-component
        garden.sapcloud.io/role: system-component
        app: vpn-shoot
        type: tunnel
    spec:
      automountServiceAccountToken: false
      serviceAccountName: vpn-shoot
      priorityClassName: system-cluster-critical
      nodeSelector:
        worker.gardener.cloud/system-components: "true"
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: vpn-shoot
        image: {{ index .Values.images "vpn-shoot" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NETWORK
          value: "{{ (split "," .Values.serviceNetwork)._0 }}"
        - name: POD_NETWORK
          value: "{{ (split "," .Values.podNetwork)._0 }}"
        {{- if .Values.nodeNetwork }}
        - name: NODE_NETWORK
          value: {{ .Values.nodeNetwork }}
        {{- end }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
          {{- if .Values.global.vpaEnabled }}
            cpu: 400m
            memory: 400Mi
          {{- else }}
            cpu: "1"
            memory: 1Gi
          {{- end }}
        volumeMounts:
        - mountPath: /srv/secrets/vpn-shoot
          name: vpn-shoot
        - mountPath: /srv/secrets/tlsauth
          name: vpn-shoot-tlsauth
        - mountPath: /srv/secrets/dh
          name: vpn-shoot-dh
      volumes:
      - name: vpn-shoot
        secret:
          secretName: vpn-shoot
      - name: vpn-shoot-tlsauth
        secret:
          secretName: vpn-shoot-tlsauth
      - name: vpn-shoot-dh
        secret:
          secretName: vpn-shoot-dh
