---
apiVersion: v1
kind: Service
metadata:
  name: vpn-shoot
  namespace: kube-system
  labels:
    app: vpn-shoot
spec:
  ipFamily: IPv6
  selector:
    app: vpn-shoot
  type: LoadBalancer
  ports:
  - name: openvpn
    protocol: TCP
    port: 4314
    targetPort: 1194
