apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: cluster-autoscaler
spec:
  ipFamily: IPv4
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
  selector:
    app: kubernetes
    role: cluster-autoscaler