{{- if .Values.konnectivityTunnel.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-egress-selector-configuration
  namespace: {{.Release.Namespace}}
data:
  egress-selector-configuration.yaml: |-
    apiVersion: apiserver.k8s.io/v1alpha1
    kind: EgressSelectorConfiguration
    egressSelections:
    - name: cluster
      connection:
        #proxyProtocol: GRPC
        proxyProtocol: HTTPConnect
        transport:
          uds:
            udsName: /etc/srv/kubernetes/konnectivity-server/konnectivity-server.socket
    - name: master
      connection:
        proxyProtocol: Direct
    - name: etcd
      connection:
        proxyProtocol: Direct
{{- end }}